import numpy as np
L=([1,2],[3,4])
print(L)
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A[0][1])
print(A[0,1])
print(A[:,0])
print(A.T)
print(np.exp(A))
print(np.exp(L))
print(A.dot(B))
c=np.diag([1,1,1])
print(c)